name: Github Actions test
run-name: ${{github.actor}} is testing out Github Actions
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:                                               
      - uses: actions/checkout@v4
      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Afficher la version de Python
        run: python -c "import sys; print(sys.version)"
      - name: install lint flake8
        run : pip install flake8
      - name: Linter le code avec Flake8
        run: flake8 .

      - name: Installer Nose
        run: |
          pip install nose
          nosetests # exécuter les tests
