name: Github Actions test
run-name: ${{github.actor}} is testing out Github Actions
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:                                               
      - uses: actions/checkout@v4
      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Afficher la version de Python
        run: python -c "import sys; print(sys.version)"

      - name: Installer Flake8
        run: pip install flake8

      
      - run: |
          python -m flake8 --max-line-length=120 --extend-ignore=F401 src/__init__.py

      - name: Formatter le code avec autopep8
        run: pip install autopep8 && autopep8 --in-place --recursive .
      - name: Linter le code avec Flake8
        run: flake8 .

      - name: Installer Nose
        run: |
          pip install nose
          nosetests # exécuter les tests
